### ISSUE TITLE
Missing stuff

### ISSUE THREAD

**Issue by NullDev** [flofriday/pixelFlow#2]
There is some stuff missing, which leads to an improperly loaded UI:

<img src="http://i.imgur.com/LkKeQ7w.png" />

**Comment by flofriday** [comment]
Yeah, I get that kind of a window way too often.

You get this half loaded Window because the Javascript has an error and stopped working. This is because all other elements are generated by JS.

In your case, the JS error is caused by not installed dependencies as you correctly assumed. However, there is already a package.js in the APP folder. If you change to that folder and do an `npm install` it should work.

I am sorry that this isn't mentioned in the README.md, I will fix this in the next minutes. Please tell me if a `npm install` in the `./App/` folder fixed the problem.

**Comment by NullDev** [comment]
This did indeed resolve the issue
